#!/bin/sh

#
# auto-rotate the screen and pointers
# copyright 2018 Don Bowman (db@donbowman.ca)
# Licensed under Apache License, Version 2.0

DISPLAY=:0
export DISPLAY

rotate_cursor() {
    pointers=$(xinput list | awk '/Virtual core pointer/ { printing=1 } /Virtual core keyboard/ { printing=0} { if (printing && (match($0, /ELAN/) || match($0, /Pen/) || match($0, /Touch/) )) { gsub(".*id=",""); print $1 } }')
    echo "rotate -- pointers: <<$pointers>> matrix: <<$*>>"
    for p in $pointers
    do
        xinput set-prop $p "Coordinate Transformation Matrix" $*
    done
}

monitor-sensor | awk '/Accelerometer orientation changed:/ { print $NF; fflush();}' | while read line
do
    echo $line
    # If we have external monitor connected, do not rotate
    nscreens=$(xrandr  | grep -c " connected")
    if [ $nscreens != 1 ]
    then
        line=normal
    fi

    # Set the actions to be taken for each possible orientation
    case "$line" in
        normal)
            # re-enable backlight
            dbus-send --print-reply=literal --type=method_call --system --dest=org.freedesktop.UPower /org/freedesktop/UPower/KbdBacklight org.freedesktop.UPower.KbdBacklight.SetBrightness int32:1
            xrandr --output eDP-1 --rotate normal 
            rotate_cursor 1 0 0 0 1 0 0 0 1
            ;;
        bottom-up)
            # disable backlight
            dbus-send --print-reply=literal --type=method_call --system --dest=org.freedesktop.UPower /org/freedesktop/UPower/KbdBacklight org.freedesktop.UPower.KbdBacklight.SetBrightness int32:0
            xrandr --output eDP-1 --rotate inverted 
            rotate_cursor -1 0 1 0 -1 1 0 0 1
            ;;
        right-up)
            # disable backlight
            dbus-send --print-reply=literal --type=method_call --system --dest=org.freedesktop.UPower /org/freedesktop/UPower/KbdBacklight org.freedesktop.UPower.KbdBacklight.SetBrightness int32:0
            xrandr --output eDP-1 --rotate right 
            rotate_cursor 0 1 0 -1 0 1 0 0 1
            ;;
        left-up)
            # disable backlight
            dbus-send --print-reply=literal --type=method_call --system --dest=org.freedesktop.UPower /org/freedesktop/UPower/KbdBacklight org.freedesktop.UPower.KbdBacklight.SetBrightness int32:0
            xrandr --output eDP-1 --rotate left
            rotate_cursor 0 -1 1 1 0 0 0 0 1
            ;;
    esac
done
exit 0
