#!/bin/sh
#
# auto-rotate the screen and pointers
# copyright 2018 Don Bowman (db@donbowman.ca)
# Licensed under Apache License, Version 2.0
#

# TODO: handle replacement of full path in file before copying

mkdir -p ~/.config/auto-rotate
dir=$(dirname "$(readlink -f "$0")")
cp $dir/autorotate.desktop ~/.config/autostart/
